### ISSUE TITLE
Craft 4 Migration m220330_111857_SplitSubmissionsTable failed

### ISSUE THREAD

**Issue by phillipsandoveracademy** [solspace/craft-freeform#351]
**Describe the bug or issue you're experiencing**

Migrating from Craft 3 to Craft 4, from FreeForm 3.13.9 to FreeForm 4.0.0-beta.7. The migration fails for one table with a name that is too long.

```
> create table {{%freeform_submissions_admissionAdmittedStudentChecklistNoSub_14}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_freeform_submissions_admissionAdmittedStudentChecklistNoSub_14' is too long
The SQL being executed was: CREATE TABLE `craft_freeform_submissions_admissionAdmittedStudentChecklistNoSub_14` (
        `id` int(11) NOT NULL,
        `admitted_student_checklist_113` text
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(104): yii\db\Migration->createTable('{{%freeform_sub...', Array)
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(77): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->createFormTable(14, 'admissionAdmitt...', Array)
#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->safeUp()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m220330_111857_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/craft(24): yii\base\Application->run()
#18 {main}
*** failed to apply m220330_111857_SplitSubmissionsTable (time: 3.382s)
```

Is this an issue that I can resolve before migration? or is this a bug?

Also, when I rerun the migrations, it fails as a table already exists.

```
*** applying m220330_111857_SplitSubmissionsTable
    > create table {{%freeform_submissions_composerForm_1}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_freeform_submissions_composerForm_1' already exists
The SQL being executed was: CREATE TABLE `craft_freeform_submissions_composerForm_1` (
        `id` int(11) NOT NULL,
        `first_name_1` text,
        `last_name_2` text,
        `email_3` text,
        `state_10` text,
        `message_12` text
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(104): yii\db\Migration->createTable('{{%freeform_sub...', Array)
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(77): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->createFormTable(1, 'composerForm', Array)
#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->safeUp()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m220330_111857_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/craft(24): yii\base\Application->run()
#18 {main}
*** failed to apply m220330_111857_SplitSubmissionsTable (time: 0.026s)
```

Is the second behavior due to the first issue? or a new issue?

**Steps to reproduce**
Follow the [Craft 4 upgrade](https://craftcms.com/docs/4.x/upgrade.html#preparing-for-the-upgrade) process.
1. Run `composer install` or `composer update`2. 
2. If install doesn't have post-craft-update scripts, run `php craft migrate/all`

**Expected behavior**
Craft FreeForm migration successful.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.2
- Freeform Version: 4.0.0-beta.7
- Freeform Edition: Craft
- Fresh Install or Upgrade: Upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @phillipsandoveracademy.

This is a bug with Freeform where we didn't account for database table prefixes when truncated longer handles. We've just released beta 8 which includes a fix for this.

In your case, you should revert back to Craft 3 and Freeform 3, and then try the migration again once grabbing the latest version of Freeform. 🙂

**Comment by phillipsandoveracademy** [comment]
Thanks @kjmartens. I migrated back to Craft 3 and did a Craft 4 upgrade (several times) with craft-freeform `4.0.0-beta.8`. I am still getting the same issue where the FreeForm migration fails on `m220330_111857_SplitSubmissionsTable`. Not sure if this is just our setup or if I should alter the form name to not cause this issue. Much appreciated!

```
> create table {{%freeform_submissions_admissionAdmittedStudentChecklistNoSub_14}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'craft_freeform_submissions_admissionAdmittedStudentChecklistNoSub_14' is too long
The SQL being executed was: CREATE TABLE `craft_freeform_submissions_admissionAdmittedStudentChecklistNoSub_14` (
        `id` int(11) NOT NULL,
        `admitted_student_checklist_113` text
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `c...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `c...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(104): yii\db\Migration->createTable('{{%freeform_sub...', Array)
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m220330_111857_SplitSubmissionsTable.php(77): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->createFormTable(14, 'admissionAdmitt...', Array)
#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): Solspace\Freeform\migrations\m220330_111857_SplitSubmissionsTable->safeUp()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(360): yii\console\controllers\BaseMigrateController->migrateUp('m220330_111857_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /var/www/html/craft(24): yii\base\Application->run()
#18 {main}
```

**Comment by kjmartens** [comment]
@phillipsandoveracademy Sorry about this. I will check further into why it doesn't seem to be working for you. In the meantime, a very simple workaround on your end would be to shorten the handle of the form on the Craft 3 site (and any others), run the migration, and then you can make the handle longer again after migration. 🙂
